/**
 * @generated — Stub for Node.js compatibility.
 * In Bun builds this is generated by scripts/generate-sdk-types.ts.
 * For Node.js dev mode, types are exported as loose placeholders.
 * Runtime validation is handled by coreSchemas.ts (Zod).
 */

import type { z } from 'zod/v4'

// Re-export schema types as their inferred types where possible,
// falling back to loose types for complex unions/mapped types.
export type ModelUsageSchema = Record<string, unknown>
export type OutputFormatTypeSchema = 'json_schema'
export type BaseOutputFormatSchema = { type: OutputFormatTypeSchema }
export type JsonSchemaOutputFormatSchema = { type: 'json_schema'; schema: Record<string, unknown> }
export type OutputFormatSchema = JsonSchemaOutputFormatSchema
export type ApiKeySourceSchema = 'user' | 'project' | 'org' | 'temporary' | 'oauth'
export type ConfigScopeSchema = 'local' | 'user' | 'project'
export type SdkBetaSchema = 'context-1m-2025-08-07'
export type ThinkingAdaptiveSchema = { type: 'adaptive' }
export type ThinkingEnabledSchema = { type: 'enabled'; budgetTokens?: number }
export type ThinkingDisabledSchema = { type: 'disabled' }
export type ThinkingConfigSchema = ThinkingAdaptiveSchema | ThinkingEnabledSchema | ThinkingDisabledSchema

export type McpStdioServerConfigSchema = { type?: 'stdio'; command: string; args?: string[]; env?: Record<string, string> }
export type McpSSEServerConfigSchema = { type: 'sse'; url: string; headers?: Record<string, string> }
export type McpHttpServerConfigSchema = { type: 'http'; url: string; headers?: Record<string, string> }
export type McpSdkServerConfigSchema = { type: 'sdk'; name: string }
export type McpServerConfigForProcessTransportSchema = McpStdioServerConfigSchema | McpSSEServerConfigSchema | McpHttpServerConfigSchema | McpSdkServerConfigSchema
export type McpClaudeAIProxyServerConfigSchema = { type: 'claudeai-proxy'; url: string; id: string }
export type McpServerStatusConfigSchema = McpServerConfigForProcessTransportSchema | McpClaudeAIProxyServerConfigSchema

export type McpServerStatusSchema = {
  name: string
  status: 'connected' | 'failed' | 'needs-auth' | 'pending' | 'disabled'
  serverInfo?: { name: string; version: string }
  error?: string
  config?: McpServerStatusConfigSchema
  scope?: string
  tools?: Array<{ name: string; description?: string; annotations?: { readOnly?: boolean; destructive?: boolean; openWorld?: boolean } }>
  capabilities?: { experimental?: Record<string, unknown> }
}

export type McpSetServersResultSchema = { added: string[]; removed: string[]; errors: Record<string, string> }

export type PermissionUpdateDestinationSchema = 'userSettings' | 'projectSettings' | 'localSettings' | 'session' | 'cliArg'
export type PermissionBehaviorSchema = 'allow' | 'deny' | 'ask'
export type PermissionRuleValueSchema = { toolName: string; ruleContent?: string }

export type PermissionUpdateSchema =
  | { type: 'addRules'; rules: PermissionRuleValueSchema[]; behavior: PermissionBehaviorSchema; destination: PermissionUpdateDestinationSchema }
  | { type: 'replaceRules'; rules: PermissionRuleValueSchema[]; behavior: PermissionBehaviorSchema; destination: PermissionUpdateDestinationSchema }
  | { type: 'removeRules'; rules: PermissionRuleValueSchema[]; behavior: PermissionBehaviorSchema; destination: PermissionUpdateDestinationSchema }
  | { type: 'setMode'; mode: PermissionModeSchema; destination: PermissionUpdateDestinationSchema }
  | { type: 'addDirectories'; directories: string[]; destination: PermissionUpdateDestinationSchema }
  | { type: 'removeDirectories'; directories: string[]; destination: PermissionUpdateDestinationSchema }

export type PermissionDecisionClassificationSchema = 'user_temporary' | 'user_permanent' | 'user_reject'

export type PermissionResultSchema =
  | { behavior: 'allow'; updatedInput?: Record<string, unknown>; updatedPermissions?: PermissionUpdateSchema[]; toolUseID?: string; decisionClassification?: PermissionDecisionClassificationSchema }
  | { behavior: 'deny'; message: string; interrupt?: boolean; toolUseID?: string; decisionClassification?: PermissionDecisionClassificationSchema }

export type PermissionModeSchema = 'default' | 'acceptEdits' | 'bypassPermissions' | 'plan' | 'dontAsk'

export const HOOK_EVENTS = [
  'PreToolUse', 'PostToolUse', 'PostToolUseFailure', 'Notification',
  'UserPromptSubmit', 'SessionStart', 'SessionEnd', 'Stop', 'StopFailure',
  'SubagentStart', 'SubagentStop', 'PreCompact', 'PostCompact',
  'PermissionRequest', 'PermissionDenied', 'Setup', 'TeammateIdle',
  'TaskCreated', 'TaskCompleted', 'Elicitation', 'ElicitationResult',
  'ConfigChange', 'WorktreeCreate', 'WorktreeRemove',
  'InstructionsLoaded', 'CwdChanged', 'FileChanged',
] as const

export type HookEventSchema = typeof HOOK_EVENTS[number]
export type BaseHookInputSchema = { session_id: string; transcript_path: string; cwd: string; permission_mode?: string; agent_id?: string; agent_type?: string }

export type PreToolUseHookInputSchema = BaseHookInputSchema & { hook_event_name: 'PreToolUse'; tool_name: string; tool_input: unknown; tool_use_id: string }
export type PermissionRequestHookInputSchema = BaseHookInputSchema & { hook_event_name: 'PermissionRequest'; tool_name: string; tool_input: unknown; permission_suggestions?: PermissionUpdateSchema[] }
export type PostToolUseHookInputSchema = BaseHookInputSchema & { hook_event_name: 'PostToolUse'; tool_name: string; tool_input: unknown; tool_response: unknown; tool_use_id: string }
export type PostToolUseFailureHookInputSchema = BaseHookInputSchema & { hook_event_name: 'PostToolUseFailure'; tool_name: string; tool_input: unknown; tool_use_id: string; error: string; is_interrupt?: boolean }
export type PermissionDeniedHookInputSchema = BaseHookInputSchema & { hook_event_name: 'PermissionDenied'; tool_name: string; tool_input: unknown; tool_use_id: string; reason: string }
export type NotificationHookInputSchema = BaseHookInputSchema & { hook_event_name: 'Notification'; message: string; title?: string; notification_type: string }
export type UserPromptSubmitHookInputSchema = BaseHookInputSchema & { hook_event_name: 'UserPromptSubmit'; prompt: string }
export type SessionStartHookInputSchema = BaseHookInputSchema & { hook_event_name: 'SessionStart'; source: 'startup' | 'resume' | 'clear' | 'compact'; agent_type?: string; model?: string }
export type SetupHookInputSchema = BaseHookInputSchema & { hook_event_name: 'Setup'; trigger: 'init' | 'maintenance' }
export type StopHookInputSchema = BaseHookInputSchema & { hook_event_name: 'Stop'; stop_hook_active: boolean; last_assistant_message?: string }
export type StopFailureHookInputSchema = BaseHookInputSchema & { hook_event_name: 'StopFailure'; error: string; error_details?: string; last_assistant_message?: string }
export type SubagentStartHookInputSchema = BaseHookInputSchema & { hook_event_name: 'SubagentStart'; agent_id: string; agent_type: string }
export type SubagentStopHookInputSchema = BaseHookInputSchema & { hook_event_name: 'SubagentStop'; stop_hook_active: boolean; agent_id: string; agent_transcript_path: string; agent_type: string; last_assistant_message?: string }
export type PreCompactHookInputSchema = BaseHookInputSchema & { hook_event_name: 'PreCompact'; trigger: 'manual' | 'auto'; custom_instructions: string | null }
export type PostCompactHookInputSchema = BaseHookInputSchema & { hook_event_name: 'PostCompact'; trigger: 'manual' | 'auto'; compact_summary: string }
export type TeammateIdleHookInputSchema = BaseHookInputSchema & { hook_event_name: 'TeammateIdle'; teammate_name: string; team_name: string }
export type TaskCreatedHookInputSchema = BaseHookInputSchema & { hook_event_name: 'TaskCreated'; task_id: string; task_subject: string; task_description?: string; teammate_name?: string; team_name?: string }
export type TaskCompletedHookInputSchema = BaseHookInputSchema & { hook_event_name: 'TaskCompleted'; task_id: string; task_subject: string; task_description?: string; teammate_name?: string; team_name?: string }
export type ElicitationHookInputSchema = BaseHookInputSchema & { hook_event_name: 'Elicitation'; mcp_server_name: string; message: string; mode?: 'form' | 'url'; url?: string; elicitation_id?: string; requested_schema?: Record<string, unknown> }
export type ElicitationResultHookInputSchema = BaseHookInputSchema & { hook_event_name: 'ElicitationResult'; mcp_server_name: string; elicitation_id?: string; mode?: 'form' | 'url'; action: 'accept' | 'decline' | 'cancel'; content?: Record<string, unknown> }
export type ConfigChangeHookInputSchema = BaseHookInputSchema & { hook_event_name: 'ConfigChange'; source: string; file_path?: string }
export type InstructionsLoadedHookInputSchema = BaseHookInputSchema & { hook_event_name: 'InstructionsLoaded'; file_path: string; memory_type: string; load_reason: string; globs?: string[]; trigger_file_path?: string; parent_file_path?: string }
export type WorktreeCreateHookInputSchema = BaseHookInputSchema & { hook_event_name: 'WorktreeCreate'; name: string }
export type WorktreeRemoveHookInputSchema = BaseHookInputSchema & { hook_event_name: 'WorktreeRemove'; worktree_path: string }
export type CwdChangedHookInputSchema = BaseHookInputSchema & { hook_event_name: 'CwdChanged'; old_cwd: string; new_cwd: string }
export type FileChangedHookInputSchema = BaseHookInputSchema & { hook_event_name: 'FileChanged'; file_path: string; event: 'change' | 'add' | 'unlink' }

export const EXIT_REASONS = ['clear', 'resume', 'logout', 'prompt_input_exit', 'other', 'bypass_permissions_disabled'] as const
export type ExitReasonSchema = typeof EXIT_REASONS[number]
export type SessionEndHookInputSchema = BaseHookInputSchema & { hook_event_name: 'SessionEnd'; reason: ExitReasonSchema }

export type AsyncHookJSONOutputSchema = { async: true; asyncTimeout?: number }
export type PreToolUseHookSpecificOutputSchema = { hookEventName: 'PreToolUse'; permissionDecision?: PermissionBehaviorSchema; permissionDecisionReason?: string; updatedInput?: Record<string, unknown>; additionalContext?: string }
export type UserPromptSubmitHookSpecificOutputSchema = { hookEventName: 'UserPromptSubmit'; additionalContext?: string }
export type SessionStartHookSpecificOutputSchema = { hookEventName: 'SessionStart'; additionalContext?: string; initialUserMessage?: string; watchPaths?: string[] }
export type SetupHookSpecificOutputSchema = { hookEventName: 'Setup'; additionalContext?: string }
export type SubagentStartHookSpecificOutputSchema = { hookEventName: 'SubagentStart'; additionalContext?: string }
export type PostToolUseHookSpecificOutputSchema = { hookEventName: 'PostToolUse'; additionalContext?: string; updatedMCPToolOutput?: unknown }
export type PostToolUseFailureHookSpecificOutputSchema = { hookEventName: 'PostToolUseFailure'; additionalContext?: string }
export type PermissionDeniedHookSpecificOutputSchema = { hookEventName: 'PermissionDenied'; retry?: boolean }
export type NotificationHookSpecificOutputSchema = { hookEventName: 'Notification'; additionalContext?: string }
export type PermissionRequestHookSpecificOutputSchema = { hookEventName: 'PermissionRequest'; decision: { behavior: 'allow'; updatedInput?: Record<string, unknown>; updatedPermissions?: PermissionUpdateSchema[] } | { behavior: 'deny'; message?: string; interrupt?: boolean } }
export type SyncHookJSONOutputSchema = { continue?: boolean; suppressOutput?: boolean; stopReason?: string; decision?: 'approve' | 'block'; systemMessage?: string; reason?: string; hookSpecificOutput?: unknown }

export type ElicitationHookSpecificOutputSchema = { hookEventName: 'Elicitation'; action?: 'accept' | 'decline' | 'cancel'; content?: Record<string, unknown> }
export type ElicitationResultHookSpecificOutputSchema = { hookEventName: 'ElicitationResult'; action?: 'accept' | 'decline' | 'cancel'; content?: Record<string, unknown> }
export type WorktreeCreateHookSpecificOutputSchema = { hookEventName: 'WorktreeCreate'; worktreePath: string }
export type HookJSONOutputSchema = AsyncHookJSONOutputSchema | SyncHookJSONOutputSchema

export type PromptRequestOptionSchema = { key: string; label: string; description?: string }
export type PromptRequestSchema = { prompt: string; message: string; options: PromptRequestOptionSchema[] }
export type PromptResponseSchema = { prompt_response: string; selected: string }

export type SlashCommandSchema = { name: string; description: string; argumentHint: string }
export type AgentInfoSchema = { name: string; description: string; model?: string }
export type ModelInfoSchema = {
  value: string; displayName: string; description: string
  supportsEffort?: boolean; supportedEffortLevels?: ('low' | 'medium' | 'high' | 'max')[]
  supportsAdaptiveThinking?: boolean; supportsFastMode?: boolean; supportsAutoMode?: boolean
}
export type AccountInfoSchema = {
  email?: string; organization?: string; subscriptionType?: string
  tokenSource?: string; apiKeySource?: string
  apiProvider?: 'firstParty' | 'bedrock' | 'vertex' | 'foundry'
}

export type AgentMcpServerSpecSchema = string | Record<string, McpServerConfigForProcessTransportSchema>
export type AgentDefinitionSchema = {
  description: string; prompt: string
  tools?: string[]; disallowedTools?: string[]
  model?: string; mcpServers?: AgentMcpServerSpecSchema[]
  criticalSystemReminder_EXPERIMENTAL?: string
  skills?: string[]; initialPrompt?: string
  maxTurns?: number; background?: boolean
  memory?: 'user' | 'project' | 'local'
  effort?: 'low' | 'medium' | 'high' | 'max' | number
  permissionMode?: PermissionModeSchema
}

export type SettingSourceSchema = 'user' | 'project' | 'local'
export type SdkPluginConfigSchema = { type: 'local'; path: string }
export type RewindFilesResultSchema = { canRewind: boolean; error?: string; filesChanged?: string[]; insertions?: number; deletions?: number }

export type SDKAssistantMessageErrorSchema = 'authentication_failed' | 'billing_error' | 'rate_limit' | 'invalid_request' | 'server_error' | 'unknown' | 'max_output_tokens'
export type SDKStatusSchema = 'compacting' | null

export type SDKUserMessageSchema = { type: 'user'; message: unknown; parent_tool_use_id: string | null; isSynthetic?: boolean; tool_use_result?: unknown; priority?: 'now' | 'next' | 'later'; timestamp?: string; uuid?: string; session_id?: string }
export type SDKUserMessageReplaySchema = SDKUserMessageSchema & { uuid: string; session_id: string; isReplay: true }
export type SDKRateLimitInfoSchema = {
  status: 'allowed' | 'allowed_warning' | 'rejected'; resetsAt?: number
  rateLimitType?: string; utilization?: number; overageStatus?: string
  overageResetsAt?: number; overageDisabledReason?: string
  isUsingOverage?: boolean; surpassedThreshold?: number
}
export type SDKAssistantMessageSchema = { type: 'assistant'; message: unknown; parent_tool_use_id: string | null; error?: SDKAssistantMessageErrorSchema; uuid: string; session_id: string }
export type SDKRateLimitEventSchema = { type: 'rate_limit_event'; rate_limit_info: SDKRateLimitInfoSchema; uuid: string; session_id: string }
export type SDKStreamlinedTextMessageSchema = { type: 'streamlined_text'; text: string; session_id: string; uuid: string }
export type SDKStreamlinedToolUseSummaryMessageSchema = { type: 'streamlined_tool_use_summary'; tool_summary: string; session_id: string; uuid: string }
export type SDKPermissionDenialSchema = { tool_name: string; tool_use_id: string; tool_input: Record<string, unknown> }

export type SDKResultSuccessSchema = {
  type: 'result'; subtype: 'success'; duration_ms: number; duration_api_ms: number
  is_error: boolean; num_turns: number; result: string; stop_reason: string | null
  total_cost_usd: number; usage: unknown; modelUsage: Record<string, unknown>
  permission_denials: SDKPermissionDenialSchema[]; structured_output?: unknown
  fast_mode_state?: FastModeStateSchema; uuid: string; session_id: string
}

export type SDKResultErrorSchema = {
  type: 'result'; subtype: string; duration_ms: number; duration_api_ms: number
  is_error: boolean; num_turns: number; stop_reason: string | null
  total_cost_usd: number; usage: unknown; modelUsage: Record<string, unknown>
  permission_denials: SDKPermissionDenialSchema[]; errors: string[]
  fast_mode_state?: FastModeStateSchema; uuid: string; session_id: string
}

export type SDKResultMessageSchema = SDKResultSuccessSchema | SDKResultErrorSchema

export type SDKSystemMessageSchema = {
  type: 'system'; subtype: 'init'; agents?: string[]; apiKeySource: ApiKeySourceSchema
  betas?: string[]; claude_code_version: string; cwd: string; tools: string[]
  mcp_servers: Array<{ name: string; status: string }>; model: string
  permissionMode: PermissionModeSchema; slash_commands: string[]; output_style: string
  skills: string[]; plugins: Array<{ name: string; path: string; source?: string }>
  fast_mode_state?: FastModeStateSchema; uuid: string; session_id: string
}

export type SDKPartialAssistantMessageSchema = { type: 'stream_event'; event: unknown; parent_tool_use_id: string | null; uuid: string; session_id: string }
export type SDKCompactBoundaryMessageSchema = { type: 'system'; subtype: 'compact_boundary'; compact_metadata: { trigger: 'manual' | 'auto'; pre_tokens: number; preserved_segment?: { head_uuid: string; anchor_uuid: string; tail_uuid: string } }; uuid: string; session_id: string }
export type SDKStatusMessageSchema = { type: 'system'; subtype: 'status'; status: SDKStatusSchema; permissionMode?: PermissionModeSchema; uuid: string; session_id: string }
export type SDKPostTurnSummaryMessageSchema = {
  type: 'system'; subtype: 'post_turn_summary'; summarizes_uuid: string
  status_category: 'blocked' | 'waiting' | 'completed' | 'review_ready' | 'failed'
  status_detail: string; is_noteworthy: boolean; title: string; description: string
  recent_action: string; needs_action: string; artifact_urls: string[]
  uuid: string; session_id: string
}
export type SDKAPIRetryMessageSchema = {
  type: 'system'; subtype: 'api_retry'; attempt: number; max_retries: number
  retry_delay_ms: number; error_status: number | null; error: SDKAssistantMessageErrorSchema
  uuid: string; session_id: string
}
export type SDKLocalCommandOutputMessageSchema = { type: 'system'; subtype: 'local_command_output'; content: string; uuid: string; session_id: string }
export type SDKHookStartedMessageSchema = { type: 'system'; subtype: 'hook_started'; hook_id: string; hook_name: string; hook_event: string; uuid: string; session_id: string }
export type SDKHookProgressMessageSchema = { type: 'system'; subtype: 'hook_progress'; hook_id: string; hook_name: string; hook_event: string; stdout: string; stderr: string; output: string; uuid: string; session_id: string }
export type SDKHookResponseMessageSchema = { type: 'system'; subtype: 'hook_response'; hook_id: string; hook_name: string; hook_event: string; output: string; stdout: string; stderr: string; exit_code?: number; outcome: 'success' | 'error' | 'cancelled'; uuid: string; session_id: string }
export type SDKToolProgressMessageSchema = { type: 'tool_progress'; tool_use_id: string; tool_name: string; parent_tool_use_id: string | null; elapsed_time_seconds: number; task_id?: string; uuid: string; session_id: string }
export type SDKAuthStatusMessageSchema = { type: 'auth_status'; isAuthenticating: boolean; output: string[]; error?: string; uuid: string; session_id: string }
export type SDKFilesPersistedEventSchema = { type: 'system'; subtype: 'files_persisted'; files: Array<{ filename: string; file_id: string }>; failed: Array<{ filename: string; error: string }>; processed_at: string; uuid: string; session_id: string }
export type SDKTaskNotificationMessageSchema = { type: 'system'; subtype: 'task_notification'; task_id: string; tool_use_id?: string; status: 'completed' | 'failed' | 'stopped'; output_file: string; summary: string; usage?: { total_tokens: number; tool_uses: number; duration_ms: number }; uuid: string; session_id: string }
export type SDKTaskStartedMessageSchema = { type: 'system'; subtype: 'task_started'; task_id: string; tool_use_id?: string; description: string; task_type?: string; workflow_name?: string; prompt?: string; uuid: string; session_id: string }
export type SDKSessionStateChangedMessageSchema = { type: 'system'; subtype: 'session_state_changed'; state: 'idle' | 'running' | 'requires_action'; uuid: string; session_id: string }
export type SDKTaskProgressMessageSchema = { type: 'system'; subtype: 'task_progress'; task_id: string; tool_use_id?: string; description: string; usage: { total_tokens: number; tool_uses: number; duration_ms: number }; last_tool_name?: string; summary?: string; uuid: string; session_id: string }
export type SDKToolUseSummaryMessageSchema = { type: 'tool_use_summary'; summary: string; preceding_tool_use_ids: string[]; uuid: string; session_id: string }
export type SDKElicitationCompleteMessageSchema = { type: 'system'; subtype: 'elicitation_complete'; mcp_server_name: string; elicitation_id: string; uuid: string; session_id: string }
export type SDKPromptSuggestionMessageSchema = { type: 'prompt_suggestion'; suggestion: string; uuid: string; session_id: string }
export type SDKSessionInfoSchema = { sessionId: string; summary: string; lastModified: number; fileSize?: number; customTitle?: string; firstPrompt?: string; gitBranch?: string; cwd?: string; tag?: string; createdAt?: number }

export type SDKMessageSchema = SDKAssistantMessageSchema | SDKUserMessageSchema | SDKUserMessageReplaySchema | SDKResultMessageSchema | SDKSystemMessageSchema | SDKPartialAssistantMessageSchema | SDKCompactBoundaryMessageSchema | SDKStatusMessageSchema | SDKAPIRetryMessageSchema | SDKLocalCommandOutputMessageSchema | SDKHookStartedMessageSchema | SDKHookProgressMessageSchema | SDKHookResponseMessageSchema | SDKToolProgressMessageSchema | SDKAuthStatusMessageSchema | SDKTaskNotificationMessageSchema | SDKTaskStartedMessageSchema | SDKTaskProgressMessageSchema | SDKSessionStateChangedMessageSchema | SDKFilesPersistedEventSchema | SDKToolUseSummaryMessageSchema | SDKRateLimitEventSchema | SDKElicitationCompleteMessageSchema | SDKPromptSuggestionMessageSchema

export type FastModeStateSchema = 'off' | 'cooldown' | 'on'
