/**
 * @generated — Stub for Node.js compatibility.
 * In Bun builds this is generated by scripts/generate-sdk-types.ts.
 * Runtime types: callbacks, interfaces with methods, non-serializable types.
 */

import type { z } from 'zod/v4'
import type { CallToolResult, ToolAnnotations } from '@modelcontextprotocol/sdk/types.js'
import type { SDKMessage, SDKSessionInfo, SDKResultMessage, SDKUserMessage } from './coreTypes.js'

// ── Zod generics ──
export type AnyZodRawShape = z.ZodRawShape
export type InferShape<S extends AnyZodRawShape> = { [K in keyof S]: z.infer<S[K]> }

// ── Effort ──
export type EffortLevel = 'low' | 'medium' | 'high' | 'max'

// ── MCP tool definition ──
export type SdkMcpToolDefinition<Schema extends AnyZodRawShape = AnyZodRawShape> = {
  name: string
  description: string
  inputSchema: Schema
  handler: (args: InferShape<Schema>, extra: unknown) => Promise<CallToolResult>
  annotations?: ToolAnnotations
  searchHint?: string
  alwaysLoad?: boolean
}

// ── MCP server config ──
export type McpSdkServerConfigWithInstance = {
  type: 'sdk'
  name: string
  version?: string
  tools: Array<SdkMcpToolDefinition<AnyZodRawShape>>
}

// ── Query options ──
export type Options = {
  model?: string
  permissionMode?: string
  maxTurns?: number
  systemPrompt?: string
  includePartialMessages?: boolean
  forkSessionId?: string
  abortController?: AbortController
  outputFormat?: { type: string; schema?: Record<string, unknown> }
}

export type InternalOptions = Options & {
  isInternal?: boolean
  skipPermissions?: boolean
}

// ── Query return types ──
export type Query = AsyncGenerator<SDKMessage, void, unknown>
export type InternalQuery = AsyncGenerator<SDKMessage, void, unknown>

// ── Session ──
export type SDKSessionOptions = {
  dir?: string
  model?: string
  systemPrompt?: string
  permissionMode?: string
}

export type SDKSession = {
  query(prompt: string | AsyncIterable<SDKUserMessage>, options?: Options): Query
  close(): Promise<void>
  sessionId: string
}

// ── Session messages ──
export type SessionMessage = SDKMessage

export type GetSessionMessagesOptions = {
  dir?: string
  limit?: number
  offset?: number
  includeSystemMessages?: boolean
}

export type ListSessionsOptions = {
  dir?: string
  limit?: number
  offset?: number
}

export type GetSessionInfoOptions = {
  dir?: string
}

export type SessionMutationOptions = {
  dir?: string
}

export type ForkSessionOptions = {
  dir?: string
  upToMessageId?: string
  title?: string
}

export type ForkSessionResult = {
  sessionId: string
}
